"""Add cascade to student session detail

Revision ID: 46af3e763254
Revises: baeee921c94a
Create Date: 2026-08-04 14:17:59.656926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46af3e763254'
down_revision: Union[str, Sequence[str], None] = 'baeee921c94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    # On Postgres, drop_constraint requires the exact constraint name.
    # We execute raw SQL to drop the constraint safely.
    import os
    if os.environ.get("DATABASE_URL", "").startswith("postgres"):
        op.execute(
            """
            DO $$ DECLARE
                r RECORD;
            BEGIN
                FOR r IN (SELECT constraint_name 
                          FROM information_schema.table_constraints 
                          WHERE table_name='student_session_details' AND constraint_type='FOREIGN KEY') 
                LOOP
                    EXECUTE 'ALTER TABLE student_session_details DROP CONSTRAINT ' || quote_ident(r.constraint_name);
                END LOOP;
            END $$;
            """
        )
    else:
        # For SQLite batch mode or other
        with op.batch_alter_table('student_session_details') as batch_op:
            batch_op.drop_constraint('student_session_details_attendance_id_fkey', type_='foreignkey')
    op.create_foreign_key(None, 'student_session_details', 'attendance', ['attendance_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_session_details', type_='foreignkey')
    op.create_foreign_key(None, 'student_session_details', 'attendance', ['attendance_id'], ['id'])
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
