"""Restore phase 1 core tables

Revision ID: 58abb42e3483
Revises: 0ae6b4d396c8
Create Date: 2026-08-03 15:27:02.529070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58abb42e3483'
down_revision: Union[str, Sequence[str], None] = '0ae6b4d396c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
