"""Restore phase 1 missing tables

Revision ID: baeee921c94a
Revises: 0ae6b4d396c8
Create Date: 2026-08-03 16:01:43.946863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeee921c94a'
down_revision: Union[str, Sequence[str], None] = '0ae6b4d396c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
