"""Add new student fields

Revision ID: bff914e4e772
Revises: e4b95e64bb9d
Create Date: 2026-07-08 09:40:20.097507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff914e4e772'
down_revision: Union[str, Sequence[str], None] = 'e4b95e64bb9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('workflow_state', sa.String(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('secret_key', sa.String(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('rotation_interval', sa.Integer(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('attendance_sessions', 'current_qr')
    op.add_column('students', sa.Column('course', sa.String(), nullable=True))
    op.add_column('students', sa.Column('is_activated', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('activation_token', sa.String(), nullable=True))
    op.alter_column('students', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.drop_index(op.f('ix_students_register_number'), table_name='students')
    op.create_unique_constraint(None, 'students', ['activation_token'])
    op.drop_column('students', 'register_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('register_number', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_index(op.f('ix_students_register_number'), 'students', ['register_number'], unique=1)
    op.alter_column('students', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_column('students', 'activation_token')
    op.drop_column('students', 'is_activated')
    op.drop_column('students', 'course')
    op.add_column('attendance_sessions', sa.Column('current_qr', sa.VARCHAR(), nullable=True))
    op.drop_column('attendance_sessions', 'is_active')
    op.drop_column('attendance_sessions', 'rotation_interval')
    op.drop_column('attendance_sessions', 'secret_key')
    op.drop_column('attendance', 'workflow_state')
    # ### end Alembic commands ###
