"""Update feedback schema

Revision ID: ea0d159db32b
Revises: bff914e4e772
Create Date: 2026-07-11 11:36:55.331127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0d159db32b'
down_revision: Union[str, Sequence[str], None] = 'bff914e4e772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_session_details', sa.Column('interactive_rating', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('student_session_details', sa.Column('relevant_rating', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('student_session_details', sa.Column('learned_today', sa.String(), nullable=False, server_default='None'))
    op.add_column('student_session_details', sa.Column('key_takeaway', sa.String(), nullable=False, server_default='None'))
    op.add_column('student_session_details', sa.Column('overall_satisfaction', sa.Integer(), nullable=False, server_default='5'))
    op.drop_column('student_session_details', 'feedback_comments')
    op.drop_column('student_session_details', 'seat_number')
    op.drop_column('student_session_details', 'feedback_rating')
    op.drop_column('student_session_details', 'need_follow_up')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_session_details', sa.Column('need_follow_up', sa.BOOLEAN(), nullable=True))
    op.add_column('student_session_details', sa.Column('feedback_rating', sa.INTEGER(), nullable=True))
    op.add_column('student_session_details', sa.Column('seat_number', sa.VARCHAR(), nullable=True))
    op.add_column('student_session_details', sa.Column('feedback_comments', sa.VARCHAR(), nullable=True))
    op.drop_column('student_session_details', 'overall_satisfaction')
    op.drop_column('student_session_details', 'key_takeaway')
    op.drop_column('student_session_details', 'learned_today')
    op.drop_column('student_session_details', 'relevant_rating')
    op.drop_column('student_session_details', 'interactive_rating')
    # ### end Alembic commands ###
